### ISSUE TITLE
"Default" text on dropdowns disappears on refresh

### ISSUE THREAD

**Issue by voytxt** [MrakDun-desu/BlockStacker-desu#10]
Settings > Customization

If you select on any (or all) of the dropdowns "Default" and then hit "Refresh lists", the Default text will magically disappear.

You can get it back by going back to the home screen, and then opening the customization again.

Before: 
![image](https://user-images.githubusercontent.com/65811166/182040672-68917ac3-23eb-49d0-9f3f-a75c18948509.png)
After:
![image](https://user-images.githubusercontent.com/65811166/182040674-93dabca5-da6e-4af2-9479-dc91fe57d8c1.png)

**Comment by MrakDun-desu** [comment]
Won't fix due to remaking UI soon
