### ISSUE TITLE
Pieces show up dark in queue.

### ISSUE THREAD

**Issue by PainDesu** [MrakDun-desu/BlockStacker-desu#16]
While playing ultra I reset few times and some pieces started showing up dark in queue.

![image](https://user-images.githubusercontent.com/43996537/204777232-f41162f5-cb33-4863-aae5-1b7aaa733786.png)

**Comment by MrakDun-desu** [comment]
Couldn't reproduce myself, but should nevertheless be fixed in the latest build. Check itch.io

**Comment by MrakDun-desu** [comment]
Fixed in 0.31.
