### ISSUE TITLE
Softlock after pausing and alt+tab

### ISSUE THREAD

**Issue by PainDesu** [MrakDun-desu/BlockStacker-desu#17]
I paused the game, alt tabbed and when I got back I couldn't do anything. The game didn't respond to the mouse clicks or keyboard presses

[Discord link with video](https://discord.com/channels/852817996484182027/872090108889808897/1047465037507330088).

**Comment by MrakDun-desu** [comment]
Couldn't reproduce. Maybe try specifying more?

**Comment by PainDesu** [comment]
I tried to replicate but was not sucessful. Only thing I remember was that I left the game running tabbed for a long time.
