### ISSUE TITLE
Grid and pieces don't zoom with the board

### ISSUE THREAD

**Issue by voytxt** [MrakDun-desu/BlockStacker-desu#2]
1) Start the game at 100% board zoom
2) Change it to 50% - the game looks normal now
3) Go back to the title and then back to the game - the grid and the pieces aren't properly scaled now
![image](https://user-images.githubusercontent.com/65811166/168440506-290e26cc-56ad-4d11-9b2f-b32067b677ed.png)

**Comment by MrakDun-desu** [comment]
Not only that pieces didn't scale correctly, board separators also didn't scale with the board. Fixed now and pushed to master.
