### ISSUE TITLE
Can't harddrop while holding softdrop + left

### ISSUE THREAD

**Issue by voytxt** [MrakDun-desu/BlockStacker-desu#22]
1. Hold softdrop + left in any gamemode
2. Now try to spam harddrop - it doesn't work

When holding softdrop + right, harddrop works correctly

**Comment by MrakDun-desu** [comment]
Can't seem to reproduce, any more information? What is your Diagonal Lock setting in handling?

**Comment by voytxt** [comment]
OOF, sorry, this is an issue with my keyboard, cuz it happens in Jstris as well
