### ISSUE TITLE
Default stat counter group doesn't show up in game settings

### ISSUE THREAD

**Issue by voytxt** [MrakDun-desu/BlockStacker-desu#25]
> it only updates the stat counter on selection, but since it's already selected on startup, it goes to default one
so before it fell back to default
but if you have an entry in the stat counter dictionary, it should load that group correctly

**Comment by MrakDun-desu** [comment]
Default stat counter group isn't in the stat counter dictionary, so it doesn't show up in game settings, neither in global settings. I'll add an option to view/change it in global settings and to see when it's picked in game settings.

**Comment by MrakDun-desu** [comment]
Implemented in 0.32
