### ISSUE TITLE
Sliders/buttons overlap text in settings when using aspect ratio different than 16:9

### ISSUE THREAD

**Issue by dalibor-osu** [MrakDun-desu/BlockStacker-desu#3]
Various sliders and buttons in main settings overlap text next to them when using display aspect ratio different than 16:9.
![image](https://user-images.githubusercontent.com/77931392/168443662-c0310314-61ea-4b23-8ff4-6750764fae32.png)
![image](https://user-images.githubusercontent.com/77931392/168443665-13a9f495-e6da-44d6-9f30-650ccfa73ae5.png)
![image](https://user-images.githubusercontent.com/77931392/168443677-a5b3c5c6-adf8-4eb3-ad72-6b89def38de6.png)

**Comment by MrakDun-desu** [comment]
Won't fix this issue due to this UI being only a placeholder.
