### ISSUE TITLE
Countdown won't pause when ESC is pressed.

### ISSUE THREAD

**Issue by dalibor-osu** [MrakDun-desu/BlockStacker-desu#5]
When you restart a game and press ESC before the game starts, "Elapsed time" timer starts, but piece stays in place. When you click on "Back to game" button for the first time, game freezes/pauses. When you click on it again, game resumes and piece jumps to a place where it should be according to elapsed time.

https://user-images.githubusercontent.com/77931392/168444914-f6ffbe8f-df23-4abf-9ab3-53e383b75f70.mp4

**Comment by MrakDun-desu** [comment]
All countdown issues fixed, now pushed on master.
