### ISSUE TITLE
Game stuck after opening a dropdown in pause menu

### ISSUE THREAD

**Issue by voytxt** [MrakDun-desu/BlockStacker-desu#9]
Play, Start Game, ESC, Video Settings

Now when you click on the resolution dropdown, and select something (or not) the game freezes, and you can't do anything other than vibing to the music.

![image](https://user-images.githubusercontent.com/65811166/182039991-06c554a3-f305-45e3-8c74-22a1df8de91b.png)

**Comment by voytxt** [comment]
Okay, same thing happens with other dropdowns in the pause menu (Fullscreen mode, or Video Settings > Presets)

**Comment by MrakDun-desu** [comment]
Won't fix due to UI being remade soon
